In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('StudentPerformanceFactors.csv')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   int64
 1   Attendance                  6607 non-null   int64
 2   Parental_Involvement        6607 non-null   object
 3   Access_to_Resources         6607 non-null   object
 4   Extracurricular_Activities  6607 non-null   object
 5   Sleep_Hours                 6607 non-null   int64
 6   Previous_Scores             6607 non-null   int64
 7   Motivation_Level            6607 non-null   object
 8   Internet_Access             6607 non-null   object
 9   Tutoring_Sessions           6607 non-null   int64
 10  Family_Income               6607 non-null   object
 11  Teacher_Quality             6529 non-null   object
 12  School_Type                 6607 non-null   object
 13  Peer_Influence              6607 non-null   object
 14  Physical_Activity           6607 non-null   int64
 15  Learning_Disabilities       6607 non-null   object
 16  Parental_Education_Level    6517 non-null   object
 17  Distance_from_Home          6540 non-null   object
 18  Gender                      6607 non-null   object
 19  Exam_Score                  6607 non-null   int64
dtypes: int64(7), object(13)
memory usage: 1.0+ MB

In [18]:
# describe() # Generates descriptive statistics of the data, including count, mean, std, min, max, and quantiles.
df.describe()

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Physical_Activity,Exam_Score
count,6607.000000,6607.000000,6607.00000,6607.000000,6607.000000,6607.000000,6607.000000
mean,19.975329,79.977448,7.02906,75.070531,1.493719,2.967610,67.235659
std,5.990594,11.547475,1.46812,14.399784,1.230570,1.031231,3.890456
min,1.000000,60.000000,4.00000,50.000000,0.000000,0.000000,55.000000
25%,16.000000,70.000000,6.00000,63.000000,1.000000,2.000000,65.000000
50%,20.000000,80.000000,7.00000,75.000000,1.000000,3.000000,67.000000
75%,24.000000,90.000000,8.00000,88.000000,2.000000,4.000000,69.000000
max,44.000000,100.000000,10.00000,100.000000,8.000000,6.000000,101.000000

In [16]:
# Include only object data  type
df.describe(include=['object'])

,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Motivation_Level,Internet_Access,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender
count,6607,6607,6607,6607,6607,6607,6529,6607,6607,6607,6517,6540,6607
unique,3,3,2,3,2,3,3,2,3,2,3,3,2
top,Medium,Medium,Yes,Medium,Yes,Low,Medium,Public,Positive,No,High School,Near,Male
freq,3362,3319,3938,3351,6108,2672,3925,4598,2638,5912,3223,3884,3814

In [17]:
# Include only number data type 
df.describe(include=['number'])

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Physical_Activity,Exam_Score
count,6607.000000,6607.000000,6607.00000,6607.000000,6607.000000,6607.000000,6607.000000
mean,19.975329,79.977448,7.02906,75.070531,1.493719,2.967610,67.235659
std,5.990594,11.547475,1.46812,14.399784,1.230570,1.031231,3.890456
min,1.000000,60.000000,4.00000,50.000000,0.000000,0.000000,55.000000
25%,16.000000,70.000000,6.00000,63.000000,1.000000,2.000000,65.000000
50%,20.000000,80.000000,7.00000,75.000000,1.000000,3.000000,67.000000
75%,24.000000,90.000000,8.00000,88.000000,2.000000,4.000000,69.000000
max,44.000000,100.000000,10.00000,100.000000,8.000000,6.000000,101.000000

In [19]:
# Include all data ttype 
df.describe(include='all')

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
count,6607.000000,6607.000000,6607,6607,6607,6607.00000,6607.000000,6607,6607,6607.000000,6607,6529,6607,6607,6607.000000,6607,6517,6540,6607,6607.000000
unique,NaN,NaN,3,3,2,NaN,NaN,3,2,NaN,3,3,2,3,NaN,2,3,3,2,NaN
top,NaN,NaN,Medium,Medium,Yes,NaN,NaN,Medium,Yes,NaN,Low,Medium,Public,Positive,NaN,No,High School,Near,Male,NaN
freq,NaN,NaN,3362,3319,3938,NaN,NaN,3351,6108,NaN,2672,3925,4598,2638,NaN,5912,3223,3884,3814,NaN
mean,19.975329,79.977448,NaN,NaN,NaN,7.02906,75.070531,NaN,NaN,1.493719,NaN,NaN,NaN,NaN,2.967610,NaN,NaN,NaN,NaN,67.235659
std,5.990594,11.547475,NaN,NaN,NaN,1.46812,14.399784,NaN,NaN,1.230570,NaN,NaN,NaN,NaN,1.031231,NaN,NaN,NaN,NaN,3.890456
min,1.000000,60.000000,NaN,NaN,NaN,4.00000,50.000000,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,55.000000
25%,16.000000,70.000000,NaN,NaN,NaN,6.00000,63.000000,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,NaN,65.000000
50%,20.000000,80.000000,NaN,NaN,NaN,7.00000,75.000000,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,3.000000,NaN,NaN,NaN,NaN,67.000000
75%,24.000000,90.000000,NaN,NaN,NaN,8.00000,88.000000,NaN,NaN,2.000000,NaN,NaN,NaN,NaN,4.000000,NaN,NaN,NaN,NaN,69.000000
max,44.000000,100.000000,NaN,NaN,NaN,10.00000,100.000000,NaN,NaN,8.000000,NaN,NaN,NaN,NaN,6.000000,NaN,NaN,NaN,NaN,101.000000

In [3]:
# selection specific percentiles
df.describe(percentiles=[0.1, 0.5, 0.9])

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Physical_Activity,Exam_Score
count,6607.000000,6607.000000,6607.00000,6607.000000,6607.000000,6607.000000,6607.000000
mean,19.975329,79.977448,7.02906,75.070531,1.493719,2.967610,67.235659
std,5.990594,11.547475,1.46812,14.399784,1.230570,1.031231,3.890456
min,1.000000,60.000000,4.00000,50.000000,0.000000,0.000000,55.000000
10%,12.000000,64.000000,5.00000,55.000000,0.000000,2.000000,63.000000
50%,20.000000,80.000000,7.00000,75.000000,1.000000,3.000000,67.000000
90%,28.000000,96.000000,9.00000,95.000000,3.000000,4.000000,72.000000
max,44.000000,100.000000,10.00000,100.000000,8.000000,6.000000,101.000000

In [21]:
#  Using describe on a non-numerical column 
df['Parental_Education_Level'].describe()

count            6517
unique              3
top       High School
freq             3223
Name: Parental_Education_Level, dtype: object

In [25]:
# Descriptive Statistics

df['Exam_Score'].mean() # Computes the mean of the data. The column should be a numeric ddatatype
df['Exam_Score'].median() # Computes the median of the data. The column should be a numeric ddatatype
df.mode() # Returns the mode(s) of the data.
df['Exam_Score'].std() # Computes the standard deviation of the data.
df['Exam_Score'].var() # Computes the variance of the data.
df['Exam_Score'].min() # Returns the minimum value of the data.
df['Exam_Score'].max() # Returns the maximum value of the data.
df['Exam_Score'].sum() # Returns the sum of the values.
df['Exam_Score'].prod() # Returns the product of the values.
df['Exam_Score'].quantile() # Computes the value at the given quantile. The default is 0.5 or 50%
df.count() # Counts the number of non#null values.
df['Exam_Score'].cumsum() # Returns the cumulative sum.
df['Exam_Score'].cumprod() # Returns the cumulative product.
df['Exam_Score'].cummax() # Returns the cumulative maximum.
df['Exam_Score'].cummin() # Returns the cumulative minimum.


# Correlation and Covariance

df['Exam_Score'].corr(df['Attendance'])  # Computes the pairwise correlation of columns, excluding NA/null values.
df['Exam_Score'].cov(df['Attendance']) # Computes the pairwise covariance of columns, excluding NA/null values.



# Other Statistical Methods

df['Exam_Score'].skew() # Computes the skewness of the data (a measure of asymmetry).
df['Exam_Score'].kurt() # Computes the kurtosis (a measure of tailedness) of the data.
df['Exam_Score'].sem() # Computes the standard error of the mean.
df['Exam_Score'].abs() # Computes the absolute value of each element.

0       67
1       61
2       74
3       71
4       70
        ..
6602    68
6603    69
6604    68
6605    68
6606    64
Name: Exam_Score, Length: 6607, dtype: int64

In [28]:
df['Exam_Score'].mode()

0    68
Name: Exam_Score, dtype: int64